apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets
  namespace: my-namespace
spec:
  provider: azure

  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: '11b4f1dc-********************'
    keyvaultName: 'myvalut-stg'
    cloudName: 'AzurePublicCloud'
    tenantId: 'e2779e10-54e2-**********************'

    objects: |
      array:
        - |
          objectName: sdkfjhSecretKey
          objectType: secret
        - |
          objectName: mysfjdsBaseUrl
          objectType: secret
        - |
          objectName: applicationName
          objectType: secret
        - |
          objectName: bucketName
          objectType: secret
        - |
          objectName: callCenterAgent
          objectType: secret
