apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-account.yaml

# Define the image name that will be referenced in deployment
images:
  - name: My-app-BE-FE


