apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auraverse-secrets
  namespace: salik
spec:
  provider: azure

  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: '09c4371a-04d2-49a3-8827-3fdd47c16493'
    keyvaultName: 'my-app-BE-FE-qa'
    cloudName: 'AzurePublicCloud'
    tenantId: 'e2779e10-54e2-4fab-b08e-00ea2de9bae7'

    objects: |
      array:
        - |
          objectName: sdlfkjdsfdsSecretKey
          objectType: secret
        - |
          objectName: ssfjdskfApiBaseUrl
          objectType: secret
        - |
          objectName: applicationName
          objectType: secret
        - |
          objectName: bucketName
          objectType: secret
        - |
          objectName: callCenterAgent
          objectType: secret
